# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marginalize_ <- function(x, xval, xvar, y) {
    .Call('_sparr_marginalize_', PACKAGE = 'sparr', x, xval, xvar, y)
}

merge_disjoint_ <- function(x, y, xval, yval, xvar, yvar) {
    .Call('_sparr_merge_disjoint_', PACKAGE = 'sparr', x, y, xval, yval, xvar, yvar)
}

merge_ <- function(x, y, xval, yval, xvar, yvar, op = "*") {
    .Call('_sparr_merge_', PACKAGE = 'sparr', x, y, xval, yval, xvar, yvar, op)
}

paste_cols <- function(A) {
    .Call('_sparr_paste_cols', PACKAGE = 'sparr', A)
}

next_cell_ <- function(cell, dim, fixed_indices) {
    .Call('_sparr_next_cell_', PACKAGE = 'sparr', cell, dim, fixed_indices)
}

set_intersect <- function(v1, v2) {
    .Call('_sparr_set_intersect', PACKAGE = 'sparr', v1, v2)
}

set_diff <- function(v1, v2) {
    .Call('_sparr_set_diff', PACKAGE = 'sparr', v1, v2)
}

set_issubeq <- function(a, b) {
    .Call('_sparr_set_issubeq', PACKAGE = 'sparr', a, b)
}

set_in <- function(a, b) {
    .Call('_sparr_set_in', PACKAGE = 'sparr', a, b)
}

set_int <- function(a, b) {
    .Call('_sparr_set_int', PACKAGE = 'sparr', a, b)
}

